hydra:
  run:
    dir: /results

type: classification

model:
  hidden_dim: 512
  feature_layers: [1024]
  xyz_feature_layers: []
  grasp_layers: [256, 256]
  final_fc_layers: [256, 256]
  text_feature_layers: [1024]
  rgb_encoder:
    frozen: true
  xyz_encoder:
    num_layers: 4
    num_heads: 4
    hidden_dim: 768
    mlp_dim: 3072
  text_encoder:
    max_length: 256
    frozen: true
  transformer:
    nhead: 4
    num_encoder_layers: 3

train:
  dataloader:
    batch_size: 128
    num_workers: 12
  dataset:
    augment: true
    augmentation_params:
      color_jitter_prob: 0.8
      gray_scale_prob: 0.1
      horizontal_flip_prob: 0.5
      flip_grasp_prob: 0.5
    data_dir: /data
    csv_path: /dataset/dataset.csv
  optimizer:
    lr: 0.00005
    weight_decay: 0.0
  test:
    frac: 0.2
    period: 500
  lr_schedule:
    warmup_steps: 1
    final_factor: 0.2
  steps: 50000
  save_period: 2500
  seed: 42
  grad_scaler:
    enabled: true
  autocast:
    enabled: true
