hydra:
  run:
    dir: /results

grasp_encoder:
  embed_dim: 4096
  hidden_dim: 512
  feature_layers: [2048, 2048]
  xyz_layers: [256, 256]
  grasp_layers: [256, 256]
  final_fc_layers: [2048, 2048]
  train_vision_model: false
  transformer:
    nhead: 4
    num_encoder_layers: 3

train:
  dataloader:
    batch_size: 128
    num_workers: 6
  dataset:
    augment: true
    augmentation_params:
      color_jitter_prob: 0.8
      gray_scale_prob: 0.1
      horizontal_flip_prob: 0.5
      flip_grasp_prob: 0.5
    data_dir: /data
    csv_path: /dataset/dataset.csv
    text_embedding_path: /dataset/text_embeddings.npy
  optimizer:
    lr: 0.0001
    # weight_decay: 0.0
  test:
    frac: 0.2
    period: 500
  lr_schedule:
    warmup_steps: 15000
    final_factor: 0.2
  steps: 50000
  save_period: 2500
  seed: 42
