hydra:
  run:
    dir: /results

defaults:
  - model/xyz_encoder: vit
  - _self_

type: regression

model:
  embed_dim: 4096
  hidden_dim: 512
  feature_layers: [1024]
  xyz_feature_layers: [1024]
  grasp_layers: [256, 256]
  final_fc_layers: [2048, 2048]
  rgb_encoder:
    frozen: true
  transformer:
    nhead: 4
    num_encoder_layers: 3

train:
  distributed:
    world_size:  # will be populated by code
  dataloader:
    batch_size: 512  # effective (will be divided by world size)
    num_workers: 16  # effective (will be divided by world size)
  dataset:
    augment: true
    augmentation_params:
      color_jitter_prob: 0.8
      gray_scale_prob: 0.1
      horizontal_flip_prob: 0.5
      flip_grasp_prob: 0.5
    data_dir: /data/observations
    csv_path: /dataset/dataset.csv
    text_embedding_path: /dataset/text_embeddings.npy
  optimizer:
    lr: 0.00005
    weight_decay: 0.0
  test:
    frac: 0.2
    period: 500
  lr_schedule:
    warmup_steps: 100
    final_factor: 0.2
  steps: 50000
  save_period: 2500
  seed: 42
