hydra:
  run:
    dir: /results

grasp_encoder:
  embed_dim: 4096
  xyz_layers: [512, 1024]
  grasp_layers: [512, 1024]
  train_vision_model: false
  transformer:
    nhead: 8
    num_encoder_layers: 3
    num_decoder_layers: 3

train:
  dataloader:
    batch_size: 48
    num_workers: 4
  dataset:
    augment: false
    augmentation_params:
      color_jitter_prob: 0.8
      gray_scale_prob: 0.1
      horizontal_flip_prob: 0.5
      flip_grasp_prob: 0.5
    data_dir: /data
    csv_path: /dataset/dataset.csv
    text_embedding_path: /dataset/text_embeddings.npy
  optimizer:
    lr: 0.001
    weight_decay: 0.0001
  epochs: 100
  save_period: 10
